SUPPLY_ITEMS = [
    {"name": "Trauma Kit",      "weight": 12, "volume": 15, "value": 90,  "category": "Medical",   "desc": "Hemorrhage control, bandages, IV fluids"},
    {"name": "Plasma Supply",   "weight": 5,  "volume": 5,  "value": 80,  "category": "Medical",   "desc": "4 units universal blood plasma"},
    {"name": "Defibrillator",   "weight": 6,  "volume": 8,  "value": 95,  "category": "Medical",   "desc": "Automated external AED unit"},
    {"name": "Oxygen Tank",     "weight": 14, "volume": 20, "value": 110, "category": "Medical",   "desc": "Medical O2, 2000 L capacity"},
    {"name": "First Aid Box",   "weight": 4,  "volume": 8,  "value": 55,  "category": "Medical",   "desc": "WHO standard first-aid supplies"},
    {"name": "Surgical Kit",    "weight": 8,  "volume": 10, "value": 105, "category": "Medical",   "desc": "Field surgery instruments & sterile pack"},
    {"name": "Ventilator",      "weight": 10, "volume": 15, "value": 120, "category": "Medical",   "desc": "Portable ICU ventilator, 8-hr battery"},
    {"name": "Antibiotics",     "weight": 3,  "volume": 3,  "value": 70,  "category": "Medical",   "desc": "Broad-spectrum IV antibiotics course"},
    {"name": "Morphine Pack",   "weight": 2,  "volume": 2,  "value": 65,  "category": "Medical",   "desc": "Controlled pain management supplies"},
    {"name": "Blood Bank",      "weight": 11, "volume": 18, "value": 100, "category": "Medical",   "desc": "Portable blood storage"},
    {"name": "Burn Kit",        "weight": 4,  "volume": 6,  "value": 60,  "category": "Medical",   "desc": "Advanced burn dressings"},
    {"name": "Mobile X-Ray",    "weight": 25, "volume": 30, "value": 140, "category": "Medical",   "desc": "Portable imaging device"},
    {"name": "Generator",       "weight": 42, "volume": 60, "value": 150, "category": "Power",     "desc": "800W portable diesel generator"},
    {"name": "Solar Array",     "weight": 18, "volume": 25, "value": 85,  "category": "Power",     "desc": "Foldable 400W solar panel set"},
    {"name": "Battery Bank",    "weight": 9,  "volume": 12, "value": 60,  "category": "Power",     "desc": "20 kWh lithium emergency battery"},
    {"name": "Thermal Camera",  "weight": 3,  "volume": 3,  "value": 75,  "category": "Power",     "desc": "FLIR thermal imager for search & rescue"},
    {"name": "Fuel Canister",   "weight": 15, "volume": 22, "value": 50,  "category": "Power",     "desc": "20L diesel container"},
    {"name": "Water Purifier",  "weight": 8,  "volume": 10, "value": 100, "category": "Survival",  "desc": "Filters 500 L/day, removes bacteria"},
    {"name": "Food Rations",    "weight": 10, "volume": 14, "value": 65,  "category": "Survival",  "desc": "72-hr rations for 10 persons"},
    {"name": "Water Tablets",   "weight": 1,  "volume": 1,  "value": 45,  "category": "Survival",  "desc": "Iodine purification for 500 L"},
    {"name": "Emer. Blankets",  "weight": 4,  "volume": 5,  "value": 40,  "category": "Survival",  "desc": "Mylar thermal blankets x50"},
    {"name": "Thermal Suits",   "weight": 7,  "volume": 10, "value": 55,  "category": "Survival",  "desc": "Extreme-cold protection suits x4"},
    {"name": "MRE Packs",       "weight": 6,  "volume": 8,  "value": 48,  "category": "Survival",  "desc": "Meal-ready-to-eat rations x24"},
    {"name": "Camp Stove",      "weight": 3,  "volume": 4,  "value": 30,  "category": "Survival",  "desc": "Portable gas stove"},
    {"name": "Hydration Pack",  "weight": 5,  "volume": 6,  "value": 35,  "category": "Survival",  "desc": "Camelbak multi-use"},
    {"name": "Satellite Phone", "weight": 2,  "volume": 2,  "value": 50,  "category": "Comms",     "desc": "Global coverage, 72-hr battery"},
    {"name": "Scout Drone",     "weight": 5,  "volume": 6,  "value": 88,  "category": "Comms",     "desc": "Aerial recon drone, 40-min flight"},
    {"name": "Radio Set",       "weight": 4,  "volume": 4,  "value": 60,  "category": "Comms",     "desc": "Multi-channel encrypted field radio"},
    {"name": "Signal Flares",   "weight": 3,  "volume": 4,  "value": 35,  "category": "Comms",     "desc": "Maritime rescue flares x12"},
    {"name": "Rope & Harness",  "weight": 7,  "volume": 9,  "value": 45,  "category": "Rescue",    "desc": "50 m rope + 4 harnesses"},
    {"name": "Hydraulic Jaws",  "weight": 20, "volume": 25, "value": 95,  "category": "Rescue",    "desc": "Hydraulic rescue spreader/cutter"},
    {"name": "Life Vests",      "weight": 6,  "volume": 8,  "value": 50,  "category": "Rescue",    "desc": "Inflatable life jackets x10"},
    {"name": "Gas Masks",       "weight": 8,  "volume": 10, "value": 70,  "category": "Rescue",    "desc": "CBRN protection masks x4"},
    {"name": "Rescue Ladder",   "weight": 12, "volume": 18, "value": 58,  "category": "Rescue",    "desc": "Extending aluminium ladder 8 m"},
    {"name": "Chainsaw",        "weight": 11, "volume": 14, "value": 80,  "category": "Rescue",    "desc": "Gas powered chainsaw"},
    {"name": "Bolt Cutters",    "weight": 5,  "volume": 5,  "value": 40,  "category": "Rescue",    "desc": "Heavy duty cutters"},
    {"name": "Stretcher",       "weight": 9,  "volume": 12, "value": 60,  "category": "Transport", "desc": "Folding aluminium stretcher"},
    {"name": "Spine Board",     "weight": 5,  "volume": 7,  "value": 72,  "category": "Transport", "desc": "Rigid spinal immobilisation board"},
    {"name": "Wheelchair",      "weight": 14, "volume": 20, "value": 42,  "category": "Transport", "desc": "Folding manual wheelchair"},
    {"name": "Evac Sled",       "weight": 6,  "volume": 8,  "value": 65,  "category": "Transport", "desc": "Lightweight snow/mud sled"},
    {"name": "Medical Tent",    "weight": 18, "volume": 28, "value": 70,  "category": "Shelter",   "desc": "6-person field medical shelter"},
    {"name": "Tarpaulin Set",   "weight": 8,  "volume": 10, "value": 38,  "category": "Shelter",   "desc": "Heavy-duty tarps x5, 5x8 m each"},
    {"name": "Sleeping Bags",   "weight": 10, "volume": 14, "value": 44,  "category": "Shelter",   "desc": "Thermal sleeping bags x8, -20C rated"},
    {"name": "Heater Unit",     "weight": 12, "volume": 16, "value": 50,  "category": "Shelter",   "desc": "Kerosene tent heater"},
    {"name": "Night Vision",    "weight": 4,  "volume": 4,  "value": 82,  "category": "Special",   "desc": "Gen-3 night-vision goggles x2"},
    {"name": "Rad Meter",       "weight": 2,  "volume": 2,  "value": 68,  "category": "Special",   "desc": "Radiation detection & dosimetry"},
    {"name": "Chem Suit Set",   "weight": 6,  "volume": 9,  "value": 78,  "category": "Special",   "desc": "Level-B chemical protection suits x2"},
    {"name": "EMP Shield",      "weight": 5,  "volume": 6,  "value": 60,  "category": "Special",   "desc": "EMP shielding box"}
]

CATEGORY_COLORS = {
    "Medical":   (215,  55,  75),
    "Power":     (255, 185,  30),
    "Survival":  ( 38, 200,  95),
    "Comms":     ( 38, 155, 255),
    "Transport": (155,  95, 245),
    "Shelter":   ( 95, 178,  75),
    "Rescue":    (255, 128,  38),
    "Special":   (220,  78, 220),
}

CAT_ABBREV = {
    "Medical":   "M",
    "Power":     "P",
    "Survival":  "S",
    "Comms":     "C",
    "Transport": "T",
    "Shelter":   "H",
    "Rescue":    "R",
    "Special":   "X",
}